name: runAll
trigger:
- master
stages:
- stage: stage1
  displayName: stage1
  jobs:
  - job: job1
    steps:
    - task: PowerShell@2
      inputs:
        targetType: 'filePath'
        filePath: ./runall.ps1
        arguments: >
          $(authFull)
      displayName: 'Run tests on each agent'
      env:
        AuthFull: $(authFull)
