name: DockerTest
parameters:
- name: agentName
  type: string
  default: Z
pool:
  name: Default
  demands:
  - agent.name -equals ${{ parameters.agentName }}
steps:
- script: |
   echo '##vso[build.updatebuildnumber]$(Build.BuildId)_$(AGENT.NAME)'
   
  failOnStderr: true
  displayName: LINUX
  condition: eq(variables['Agent.OS'], 'Linux')

- script: |
   echo ##vso[build.updatebuildnumber]$(Build.BuildId)_$(AGENT.NAME)
   
  failOnStderr: true
  displayName: WINDOWS
  condition: eq(variables['Agent.OS'], 'Windows_NT')

- script: |
   docker --version
   docker run hello-world
